import React, { useState, useEffect } from 'react';
import { StudyFile } from '../../types/session';
import ViewContainer from '../ui/ViewContainer';

const ConceptMapView: React.FC<{ files: StudyFile[] }> = ({ files }) => {
  const [conceptMap, setConceptMap] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const generateConceptMap = async () => {
      if (files.length === 0) return;

      setIsLoading(true);
      setError(null);

      try {
        // For now, create a simple concept map using Mermaid
        const simpleConceptMap = `graph TD
    A[Document Analysis] --> B[Content Processing]
    A --> C[Study Tools]
    A --> D[Learning Outcomes]
    
    B --> E[Text Extraction]
    B --> F[Content Analysis]
    
    C --> G[Flashcards]
    C --> H[Quizzes]
    C --> I[Notes]
    C --> J[Chat]
    
    D --> K[Understanding]
    D --> L[Retention]
    D --> M[Application]
    
    E --> N[PDF Processing]
    E --> O[Image Analysis]
    
    F --> P[Key Concepts]
    F --> Q[Main Topics]
    F --> R[Important Details]
    
    G --> S[Active Recall]
    H --> T[Knowledge Testing]
    I --> U[Structured Learning]
    J --> V[Interactive Learning]
    
    K --> W[Comprehension]
    L --> X[Memory Retention]
    M --> Y[Real-world Application]`;
        
        setConceptMap(simpleConceptMap);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to generate concept map');
      } finally {
        setIsLoading(false);
      }
    };

    generateConceptMap();
  }, [files]);

  return (
    <ViewContainer title="Concept Map" isLoading={isLoading} error={error} generationText="Mapping out key concepts...">
      <div className="space-y-4">
        <div className="text-sm text-gray-600 dark:text-gray-400">
          This concept map shows the relationships between key concepts in your documents.
        </div>
        
        {conceptMap && (
          <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-4">
            <pre className="text-sm overflow-x-auto">
              <code className="language-mermaid">
                {conceptMap}
              </code>
            </pre>
          </div>
        )}
        
        <div className="text-xs text-gray-500 dark:text-gray-400">
          *This is a placeholder concept map. In a full implementation, this would be generated by AI analysis of your specific documents and their key concepts.*
        </div>
      </div>
    </ViewContainer>
  );
};

export default ConceptMapView; 