import React, { useState, useEffect } from 'react';
import { StudyFile } from '../../types/session';
import ViewContainer from '../ui/ViewContainer';
import MarkdownRenderer from '../ui/MarkdownRenderer';

interface StudyPlanViewProps {
  files: StudyFile[];
}

const StudyPlanView: React.FC<StudyPlanViewProps> = ({ files }) => {
  const [plan, setPlan] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const generateStudyPlan = async () => {
      if (files.length === 0) return;

      setIsLoading(true);
      setError(null);

      try {
        // For now, create a simple study plan
        const simplePlan = `# Your 7-Day Study Plan\n\n## Overview\n\nBased on your ${files.length} uploaded document(s), here's a personalized study plan to help you master the material.\n\n## Day 1: Introduction\n- **Focus**: Overview and key concepts\n- **Activities**: Read through summaries, identify main topics\n- **Time**: 30-45 minutes\n\n## Day 2: Deep Dive\n- **Focus**: Detailed content analysis\n- **Activities**: Create notes, highlight important points\n- **Time**: 45-60 minutes\n\n## Day 3: Practice\n- **Focus**: Application and understanding\n- **Activities**: Take quizzes, test knowledge\n- **Time**: 30-45 minutes\n\n## Day 4: Review\n- **Focus**: Reinforcement and clarification\n- **Activities**: Review flashcards, revisit difficult concepts\n- **Time**: 30 minutes\n\n## Day 5: Application\n- **Focus**: Real-world application\n- **Activities**: Discuss concepts, apply to examples\n- **Time**: 45 minutes\n\n## Day 6: Assessment\n- **Focus**: Self-evaluation\n- **Activities**: Take comprehensive quiz, identify gaps\n- **Time**: 30 minutes\n\n## Day 7: Mastery\n- **Focus**: Final review and confidence building\n- **Activities**: Review all materials, celebrate progress\n- **Time**: 30 minutes\n\n## Tips for Success\n\n- Study in short, focused sessions\n- Take regular breaks\n- Use active recall techniques\n- Review regularly\n- Stay consistent with your schedule\n\n*This is a placeholder study plan. In a full implementation, this would be generated by AI analysis of your specific documents and learning goals.*`;
        setPlan(simplePlan);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to generate study plan');
      } finally {
        setIsLoading(false);
      }
    };

    generateStudyPlan();
  }, [files]);

  return (
    <ViewContainer title="Your 7-Day Study Plan" isLoading={isLoading} error={error} generationText="Building your personalized study plan...">
      <MarkdownRenderer content={plan} />
    </ViewContainer>
  );
};

export default StudyPlanView; 